server:
  port: 9527

spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      routes:
        - id: payment  #路由的ID，没有固定的规则，但要求唯一性，建议配合服务名
          uri: http://localhost:8002  #匹配后提供服务的路由的地址
          predicates:
            - Path=/payment/getPaymentById/**   #断言，路径相匹配的进行路由
eureka:
  instance:
    hostname: cloud-gateway-service
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka